name: Openmrs-module-appointments - Frontend - Github actions CI/CD

on:
  push:
    branches: [ stream3/master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: define variables
        run: |
          PACKAGE_VERSION=0.0.${{ github.run_number }}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "PACKAGE_FILENAME=openmrs_appointments_app.$PACKAGE_VERSION.zip" >> $GITHUB_ENV
          echo "OCTOPUS_SERVER=https://${{ secrets.OCTOPUS_ORG }}.octopus.app/" >> $GITHUB_ENV
          echo "OCTOPUS_ENVIROMENT=QA-DEMO" >> $GITHUB_ENV

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm
        run: npm install

      - name: Test
        run: npm test

      - name: Build
        run:  npm run build

      - name: Package
        run: |
          echo "PACKAGE_FILENAME '$PACKAGE_FILENAME'"
          cd dist
          for FILE in *; do zip -r ../$PACKAGE_FILENAME $FILE; done
          cd ..

      - name: Install Octopus CLI
        run: |
          sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
          curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
          sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
          sudo apt update && sudo apt install octopuscli

      - name: Publish to octopus
        run: |
          echo "PACKAGE_FILENAME '$PACKAGE_FILENAME'"
          octo push \
            --server="$OCTOPUS_SERVER" --apiKey="${{ secrets.OCTOPUS_API_KEY }}" --space="${{ secrets.OCTOPUS_SPACE_URL_FRAGMENT }}" \
            --package="$PACKAGE_FILENAME"

      - name: Create Release and Deploy
        run: |
          octo create-release \
            --server="$OCTOPUS_SERVER" --apiKey="${{ secrets.OCTOPUS_API_KEY }}" --space="${{ secrets.OCTOPUS_SPACE_URL_FRAGMENT }}" \
            --project="openmrs-module-appointments-frontend" --packageVersion="$PACKAGE_VERSION" --deployTo="$OCTOPUS_ENVIROMENT"
